### ISSUE TITLE
Expecting 'IDENT', '[', got 'EOF'

### ISSUE THREAD

**Issue by loveJasmine** [demike/TsUML2#7]
PS C:\XXXX-web\XXXX-next\apps\XXXX-next> tsuml2 --glob "./src/XXXX-next/controls/!(*.d|*.spec).ts"
parsing source files:
C:/XXXX-web/XXXX-next/apps/XXXX-next/src/XXXX-next/controls/FabricIcons.ts
C:/XXXX-web/XXXX-next/apps/XXXX-next/src/XXXX-next/controls/FabricIconsDeferred.ts
C:/XXXX-web/XXXX-next/apps/XXXX-next/src/XXXX-next/controls/FluentHybridIcons.ts
C:/XXXX-web/XXXX-next/apps/XXXX-next/src/XXXX-next/controls/OdDeferredFont.scss.ts
C:/XXXX-web/XXXX-next/apps/XXXX-next/src/XXXX-next/controls/ODFabric.scss.ts

emitting declarations:
C:/XXXX-web/XXXX-next/apps/XXXX-next/src/XXXX-next/controls/FabricIcons.ts
C:/XXXX-web/XXXX-next/apps/XXXX-next/src/XXXX-next/controls/FabricIconsDeferred.ts
C:/XXXX-web/XXXX-next/apps/XXXX-next/src/XXXX-next/controls/FluentHybridIcons.ts
^
Expecting 'IDENT', '[', got 'EOF'
    at Parser.parseError (C:\Users\victor\AppData\Local\nvs\node\12.22.1\x64\node_modules\tsuml2\node_modules\nomnoml\dist\nomnoml.js:1397:21)
    at Parser.parse (C:\Users\victor\AppData\Local\nvs\node\12.22.1\x64\node_modules\tsuml2\node_modules\nomnoml\dist\nomnoml.js:1464:22)
    at Object.intermediateParse (C:\Users\victor\AppData\Local\nvs\node\12.22.1\x64\node_modules\tsuml2\node_modules\nomnoml\dist\nomnoml.js:340:34)
    at Object.parse (C:\Users\victor\AppData\Local\nvs\node\12.22.1\x64\node_modules\tsuml2\node_modules\nomnoml\dist\nomnoml.js:271:33)
    at Object.renderSvg (C:\Users\victor\AppData\Local\nvs\node\12.22.1\x64\node_modules\tsuml2\node_modules\nomnoml\dist\nomnoml.js:215:37)
    at Object.renderNomnomlSVG (C:\Users\victor\AppData\Local\nvs\node\12.22.1\x64\node_modules\tsuml2\dist\core\io.js:6:20)
    at Object.createNomnomlSVG (C:\Users\victor\AppData\Local\nvs\node\12.22.1\x64\node_modules\tsuml2\dist\core\index.js:59:20)
    at C:\Users\victor\AppData\Local\nvs\node\12.22.1\x64\node_modules\tsuml2\dist\bin\index.js:24:20
    at Generator.next (<anonymous>)
    at C:\Users\victor\AppData\Local\nvs\node\12.22.1\x64\node_modules\tsuml2\dist\bin\index.js:9:71 {
  hash: {
    text: '',
    token: 'EOF',
    line: 0,
    loc: { first_line: 1, first_column: 0, last_line: 1, last_column: 0 },
    expected: [ "'IDENT'", "'['" ]
  }
}
PS C:\XXXX-web\XXXX-next\apps\XXXX-next>

**Comment by demike** [comment]
Can you prepare a reproducable example? It's next to impossible to solve this problem without one.

**Comment by demike** [comment]
@loveJasmine: The error message stems from an empty nomnoml dsl (not a single entity could be found)
You can take a look at the generated nomnoml dsl file by using the `--outDsl` in a recent version
